from setuptools import find_packages, setup

setup(
    name="GravNN",
    packages=find_packages(),
    version="0.8.0",
    description="GravNN Package",
    author="John M",
    license="MIT",
    setup_requires=[
        "setuptools",
        "wheel",
    ],
    install_requires=[
        # "numpy == 1.23.0",
        # 'tensorflow>=2.6; sys_platform != "darwin"',
        # 'tensorflow-macos; sys_platform == "darwin"',
        "trimesh == 3.9.31",
        "matplotlib",
        "numba",
        "pandas",
        "scikit-learn",
        "plotly",
        "dash",
        "sigfig",
        "tqdm",
        "colorama",
        "rtree",
        "pooch",
        "seaborn",
        "spiceypy",
        "sphinx",
        "sphinx_rtd_theme",
        "sphinx-gallery",
        "pre-commit",
    ],
    tests_require=["pytest==4.4.1"],
    test_suite="tests",
)
